### ISSUE TITLE
lol - failing commands don't actually raise the fail to this process

### ISSUE THREAD

**Issue by orta** [orta/Komondor#7]
So it will always pass

**Comment by daneov** [comment]
Once a release is made this one can be closed ✅ :)

**Comment by orta** [comment]
This is shipped in 1.0.2 - as well as docs on how to ship releases if you want to give it a shot sometime @daneov

**Comment by 45ux** [comment]
https://storage1.premiumcdn.net/preview/19576703/xg3spzTmbsv4cVKuXVImzSPOSjPTBJFnluvGS8ju2gSdAur0sOnurpSJzSK0uaXTNAf2qFpJiJlsp4U7vcYzsVnt1NcBnFjyHXWCLQHK4sgZfmeiJAsQVHoXCa7cmkfQ8seYs1gUw5fWJfVwcJ0.mp4?expires=1606374646&hash=31WDWmEuT6WiB8Nt16EwXQ
